### ISSUE TITLE
Volume error

### ISSUE THREAD

**Issue by mlinaje** [gusals3587/jumpcutterV2#6] opened 2020-04-11 16:44 UTC
**First off, your system's info**

OS:
python --version:3.8.2

Traceback (most recent call last):
  File ".\jumpcutterv2\fast_video.py", line 84, in <module>
    if getMaxVolume(audioChunk) < 500:
  File ".\jumpcutterv2\fast_video.py", line 34, in getMaxVolume
    maxv = np.max(s)
  File "<__array_function__ internals>", line 5, in amax
  File "C:\Users\usuario2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\core\fromnumeric.py", line 2667, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "C:\Users\usuario2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\core\fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

**steps to reproduce**
tested with:
mp4 input file (downloaded from youtube) 
mkv input file (output from OBS)

**expected behavior**
video output file without sound (but both, the original sound file and the cutted one are the directory)

**Comment by gusals3587** [comment] 2020-04-11 23:51
duplicate of #5

**Closed as completed by gusals3587** 2020-04-11 23:51 UTC
